### ISSUE TITLE
Excel do Banco de Dados

### ISSUE THREAD

**Issue by DanielaMF** [juliameller/trabalhobd2#12]
Boa noite,

Estou disponibilizando o link do Excel para o banco de dados e seus respectivos indicies.

https://docs.google.com/spreadsheets/d/1PvjYGm6brFAbLxqvjsXiGd1f0bPf4rDt9c_I3d7OYOQ/edit?usp=sharing

**Comment by DanielaMF** [comment]
Boa tarde, em caso criação de novos indicies, deixei disponível a edição do Excel.

**Comment by juliameller** [comment]
criado em 6889a634a9af3a70ec87bcb74cf1753f27a35115

atualizado em a71252dd90380b4529d574273c68e1bfc6a8af9d
