### ISSUE TITLE
Criar novos index para as perguntas de negocio

### ISSUE THREAD

**Issue by thiagolarangeiras** [juliameller/trabalhobd2#13]
Criar novos index para as perguntas de negocio.

**Comment by weslainesantana** [comment]
criado novos indix.

-- Remoção de Índices Existentes:

DROP INDEX IF EXISTS idx_pagamento_id_pedido_status_pagamento ON pagamento 
DROP INDEX IF EXISTS idx_pedido_id_pedido_dt_pedido ON pedido;

-- Criação de Índices:

CREATE INDEX idx_pagamento_id_pedido_status_pagamento ON pagamento(id_pedido, status_pagamento) INCLUDE(total);
CREATE INDEX idx_pedido_id_pedido_dt_pedido ON pedido(dt_pedido, id_pedido);

-- Remoção de Índices Existentes:

DROP INDEX IF EXISTS idx_pedido_item_id_produto ON pedido_item;
DROP INDEX IF EXISTS idx_produto_id_produto ON produto;
DROP INDEX IF EXISTS idx_produzido_data ON produzido;
DROP INDEX IF EXISTS idx_produzido_id_produto ON produzido;

-- Criação de Novos Índices:

CREATE INDEX idx_pedido_item_id_pedido_id_produto ON pedido_item (id_pedido, id_produto) INCLUDE (quantidade);
CREATE INDEX idx_produto ON produto (id_produto) INCLUDE (quantidade);
CREATE INDEX idx_produzido_data ON produzido (id_produto, data) INCLUDE (quantidade);

**Comment by DanielaMF** [comment]
Pelo que observei foi aplicado no Excel do banco, caso venha ser criado outros, adicionar ao link na outra issue. #12

**Comment by juliameller** [comment]
fechado em b9476c966fc6ec54120b8fda82ca50540f06cf0d
